---
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  database: app_db

development:
  <<: *default
  password:

production:
  <<: *default
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>