---
defaults: &defaults
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  strict: false

development:
  <<: *defaults
  database: kubernetes-rails-example
