apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-rails-example-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: danielchapdelaine/kubernetes-rails-example:latest
        envFrom:
        - configMapRef:
            name: env
        ports:
        - containerPort: 3000
      # initContainers:
      # - name: migrations
      #   image: danielchapdelaine/kubernetes-rails-example:latest
      #   command:
      #   - rake
      #   - db:abort_if_pending_migrations